# Next Steps

The developable land inventory is one step in the broader planning process for identifying reasonable areas to develop housing under these statutes. Other elements of this process will draw on the developable land inventory, applying separate analyses of locally defined factors that enable or limit development potential, to narrow planning focus and prioritize sites, neighborhoods, or zones for potential housing growth strategies.

C.G.S. Sections 8-13bb(d) and (i), and 8-13cc(b) require OPM to issue guidelines on the “form and level of detail” required of Housing Growth Plans (HGPs) as well as the formats, mapping standards and standardized metrics for annual reporting on HGP implementation. The Secretary may amend these guidelines from time to time. These [Housing Growth Plan Guidelines](#0) can be viewed on the [2025 Act Concerning Housing Growth web page](#0) from OPM.

Per the Housing Growth Plan Guidelines, other elements of the Housing Growth Plans may draw on this developable land inventory and apply further analyses, such as a [suitability analysis](https://housingmaps.ct.gov/pages/suitability-analysis), to inform elements such as:

- Diverse Housing Types
- Accessibility for Individuals with Intellectual or Developmental Disabilities
- Parcel & Zone Identification
- Opportunities for New Affordable Units